import { Product, Promotion, Review } from './types';

export const PRODUCTS: Product[] = [
  // --- CLIENT ADDED CUSTOM PRODUCTS (LIVE PREVIEW ACCELERATION) ---
  {
    id: 'shivnak-pandey-proudct',
    name: 'shivnak pandey proudct',
    description: 'An elegant hallmark 925 sterling silver custom-crafted designer masterpiece, featuring brilliant faceted simulated diamond layers and an ultra-comfortable comfort-fit band.',
    price: 1999,
    originalPrice: 3500,
    rating: 5.0,
    reviewsCount: 382,
    image: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=600&auto=format&fit=crop&q=80&sig=shivnak-pandey',
    category: 'rings',
    bestseller: true,
    isNew: true,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her', 'For Him'],
    occasions: ['Birthday', 'Anniversary', 'Others']
  },
  // --- ORIGINAL RINGS ---
  {
    id: 'ethereal-bloom',
    name: 'Ethereal Bloom Ring',
    description: 'An elegant display of micro-pave diamond floral petals crowning a thick, hand-polished 925 sterling silver band. Hypoallergenic and highly mirror-finished.',
    price: 2499,
    originalPrice: 4200,
    rating: 4.9,
    reviewsCount: 1420,
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop&q=80',
    category: 'rings',
    bestseller: true,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Birthday', 'Anniversary']
  },
  {
    id: 'azure-wave-band',
    name: 'Azure Wave Band',
    description: 'A masterpiece ring featuring organic water waves hand-engraved into 925 sterling silver, embedded with a single pure cushion-cut blue sapphire at the crest.',
    price: 1850,
    originalPrice: 2900,
    rating: 5.0,
    reviewsCount: 423,
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop&q=80&sig=azure-wave-ring',
    category: 'rings',
    bestseller: false,
    isNew: true,
    polishColors: ['Silver', 'Rose Gold'],
    recipients: ['For Her', 'For Him'],
    occasions: ['Birthday', 'Others']
  },
  {
    id: 'imperial-solitaire',
    name: 'Imperial Solitaire',
    description: 'The epitome of simple royalty. A certified Round Brilliant cut solitaire diamond mounted on high-polished 925 sterling silver delicate prongs for premium luxury.',
    price: 3200,
    originalPrice: 5500,
    rating: 4.8,
    reviewsCount: 812,
    image: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=600&auto=format&fit=crop&q=80',
    category: 'rings',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Anniversary', 'Birthday']
  },
  {
    id: 'serpentine-twist',
    name: 'Serpentine Twist',
    description: 'An architectural layered ring composed of overlapping fine silver threads, inspired by Roman heritage. Meticulously handcrafted to form a thick, textured statement.',
    price: 1599,
    originalPrice: 2400,
    rating: 4.7,
    reviewsCount: 290,
    image: 'https://images.unsplash.com/photo-1605100827113-99147fc2b114?w=600&auto=format&fit=crop&q=80&sig=serpentine-twist',
    category: 'rings',
    bestseller: true,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold'],
    recipients: ['For Her', 'For Him'],
    occasions: ['Anniversary', 'Others']
  },
  {
    id: 'starlight-ring',
    name: 'Starlight Diamond Ring',
    description: 'A stellar high-polished 925 sterling silver solitaire ring showcasing a custom-cut, ethically sourced brilliant diamond. Mounted on elegant thin silver prongs.',
    price: 1500,
    originalPrice: 2999,
    rating: 4.9,
    reviewsCount: 420,
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop&q=80&sig=starlight-ring',
    category: 'rings',
    bestseller: true,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Anniversary', 'Birthday']
  },
  {
    id: 'minimal-band',
    name: 'Solace Minimalist Band',
    description: 'A clean, timeless 925 sterling silver band that represents structural perfection. Handcrafted under rigorous temperature controls to maintain the alloy\'s eternal density.',
    price: 999,
    originalPrice: 1999,
    rating: 4.7,
    reviewsCount: 188,
    image: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&auto=format&fit=crop&q=80',
    category: 'rings',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold'],
    recipients: ['For Her', 'For Him'],
    occasions: ['Anniversary', 'Others']
  },
  {
    id: 'empress-ring',
    name: 'Empress Halo Cushion Ring',
    description: 'Crafted with premium faceted crystals and thick 925 silver layering. Designed to reflect light from every angle, radiating a royal aura fit for any grand celebratory banquet.',
    price: 2400,
    originalPrice: 4800,
    rating: 5.0,
    reviewsCount: 74,
    image: 'https://images.unsplash.com/photo-1627293021152-73a8236203a2?w=600&auto=format&fit=crop&q=80',
    category: 'rings',
    bestseller: true,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Anniversary', 'Birthday']
  },

  // --- ADDITIONAL RINGS ---
  {
    id: 'celestial-orbit',
    name: 'Celestial Orbit Ring',
    description: 'A stellar multi-layer band designed with swirling orbits of micro-crystals and highly polished 925 premium silver. Features lightweight, skin-safe edges.',
    price: 1650,
    originalPrice: 2900,
    rating: 4.8,
    reviewsCount: 324,
    image: 'https://images.unsplash.com/photo-1571506191837-de1d0b74070a?w=600&auto=format&fit=crop&q=80',
    category: 'rings',
    bestseller: false,
    isNew: true,
    polishColors: ['Silver', 'Rose Gold'],
    recipients: ['For Her'],
    occasions: ['Birthday', 'Others']
  },
  {
    id: 'interlocking-eternity',
    name: 'Interlocking Eternity Ring',
    description: 'Two interlocking bands symbolizing infinite unity. Styled in genuine 925 silver and detailed with premium cz pave inserts. Pure sophistication.',
    price: 1950,
    originalPrice: 3500,
    rating: 4.9,
    reviewsCount: 112,
    image: 'https://images.unsplash.com/photo-1543294001-f7cbfe92237e?w=600&auto=format&fit=crop&q=80',
    category: 'rings',
    bestseller: true,
    isNew: true,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Anniversary']
  },
  {
    id: 'opulent-chevron',
    name: 'Opulent Chevron V Ring',
    description: 'A dramatic, minimalist crown-shaped Chevron ring. Expertly hand-molded to fit perfectly in nested stacks or as a standalone geometric statement.',
    price: 1450,
    originalPrice: 2300,
    rating: 4.7,
    reviewsCount: 89,
    image: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&auto=format&fit=crop&q=80',
    category: 'rings',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold'],
    recipients: ['For Her'],
    occasions: ['Others']
  },
  {
    id: 'royal-monarch-crown',
    name: 'Empress Royal Crown Ring',
    description: 'Prestige in every crown point. Intricately carved royal points set with dainty round elements in high-reflectivity silver.',
    price: 2600,
    originalPrice: 4400,
    rating: 5.0,
    reviewsCount: 145,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop&q=80',
    category: 'rings',
    bestseller: true,
    isNew: false,
    polishColors: ['Silver', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Birthday']
  },
  {
    id: 'vintage-filigree',
    name: 'Vintage Silver Filigree Ring',
    description: 'Inspired by traditional Victorian design, featuring gorgeous openwork metal patterns lace-carved into 925 sterling silver.',
    price: 1750,
    originalPrice: 3100,
    rating: 4.6,
    reviewsCount: 72,
    image: 'https://images.unsplash.com/photo-1598560917505-59a3ad559071?w=600&auto=format&fit=crop&q=80',
    category: 'rings',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver'],
    recipients: ['For Her'],
    occasions: ['Others']
  },
  {
    id: 'titan-matt-band',
    name: 'Titan Hammered Band',
    description: 'Rugged luxury for him. A solid 925 sterling silver comfort-fit ring featuring hand-hammered raw textures and an satin-finish interior.',
    price: 2100,
    originalPrice: 3800,
    rating: 4.8,
    reviewsCount: 198,
    image: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=600&auto=format&fit=crop&q=80&sig=titan-band',
    category: 'rings',
    bestseller: true,
    isNew: true,
    polishColors: ['Silver'],
    recipients: ['For Him'],
    occasions: ['Anniversary', 'Others']
  },
  {
    id: 'sigil-square-signet',
    name: 'Grand Monarch Square Signet',
    description: 'A handsome, substantial square signet ring molded in hypoallergenic silver with thick protective plating. Handcrafted for a commanding silhouette.',
    price: 2899,
    originalPrice: 4999,
    rating: 4.9,
    reviewsCount: 341,
    image: 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=600&auto=format&fit=crop&q=80',
    category: 'rings',
    bestseller: true,
    isNew: false,
    polishColors: ['Silver', 'Gold Plated'],
    recipients: ['For Him'],
    occasions: ['Birthday']
  },
  {
    id: 'test-jewel',
    name: '₹1 Sandbox Checkout Tester',
    description: 'A special testing jewelry product priced at exactly ₹1 to simulate payment gateways, Razorpay UPI requests, and automatic sync webhooks with your Shopify database without spending real capital.',
    price: 1,
    originalPrice: 10,
    rating: 5.0,
    reviewsCount: 1337,
    image: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=600&auto=format&fit=crop&q=80&sig=test-jewel-checkout',
    category: 'rings',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her', 'For Him'],
    occasions: ['Birthday', 'Others']
  },


  // --- ORIGINAL EARRINGS ---
  {
    id: 'classic-studs',
    name: 'Classic Silver Studs',
    description: 'Expertly high-polished 925 sterling silver geometric studs. Featuring custom tension backing for secure fitting, hypoallergenic composition, and a modern architectural silhouette.',
    price: 1200,
    originalPrice: 2400,
    rating: 4.8,
    reviewsCount: 956,
    image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=600&auto=format&fit=crop&q=80&sig=classic-studs',
    category: 'earrings',
    bestseller: true,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her', 'For Him'],
    occasions: ['Birthday', 'Others']
  },
  {
    id: 'gothic-hoops',
    name: 'Elysian Silver Hoops',
    description: 'Medium-weight circular hoop earrings made of hyper-pure 925 sterling silver. Extremely smooth latch locks ensure safety, making them your favorite accessory.',
    price: 1800,
    originalPrice: 3200,
    rating: 4.6,
    reviewsCount: 204,
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80',
    category: 'earrings',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Birthday', 'Others']
  },
  {
    id: 'cascade-drops',
    name: 'Verdant Cascade Drops',
    description: 'These glamorous silver earrings feature premium crystals dangling organically from an intricate filigree framework. Elegant movement meets unmatched architectural balance.',
    price: 2100,
    originalPrice: 3999,
    rating: 4.8,
    reviewsCount: 92,
    image: 'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=600&auto=format&fit=crop&q=80',
    category: 'earrings',
    bestseller: true,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold'],
    recipients: ['For Her'],
    occasions: ['Birthday', 'Anniversary']
  },

  // --- ADDITIONAL EARRINGS ---
  {
    id: 'geometric-hex-studs',
    name: 'Hexagonal Geometric Studs',
    description: 'Symmetric beauty. Sleek, faceted six-sided bezels crafted in certified 925 sterling silver. Extremely light weight and comfortable for dual piercings.',
    price: 950,
    originalPrice: 1800,
    rating: 4.5,
    reviewsCount: 114,
    image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=600&auto=format&fit=crop&q=80',
    category: 'earrings',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold'],
    recipients: ['For Her', 'For Him'],
    occasions: ['Birthday']
  },
  {
    id: 'luminous-pearl-drops',
    name: 'Luminous Fresh Pearl Drops',
    description: 'A genuine high-luster freshwater pearl suspended beautifully beneath an ornate 925 silver stud bar. Adds instant grace to both wedding and executive dresses.',
    price: 2450,
    originalPrice: 4200,
    rating: 4.9,
    reviewsCount: 389,
    image: 'https://images.unsplash.com/photo-1601121141461-9d66474ca5cd?w=600&auto=format&fit=crop&q=80',
    category: 'earrings',
    bestseller: true,
    isNew: true,
    polishColors: ['Silver', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Anniversary']
  },
  {
    id: 'constellation-climbers',
    name: 'Constellation Ear Climbers',
    description: 'An asymmetrical sweep of seven celestial star-carved diamonds climbing up the ear lobe in an elegant 925 sterling silver trail.',
    price: 1550,
    originalPrice: 2900,
    rating: 4.8,
    reviewsCount: 82,
    image: 'https://images.unsplash.com/photo-1588444839799-eb08ed7bc65b?w=600&auto=format&fit=crop&q=80',
    category: 'earrings',
    bestseller: false,
    isNew: true,
    polishColors: ['Silver', 'Rose Gold'],
    recipients: ['For Her'],
    occasions: ['Others']
  },
  {
    id: 'hammered-silver-cuffs',
    name: 'Hammered Silver Ear Cuffs',
    description: 'No piercing required. Simply slide this beautifully textured, adjustable 925 cuff onto your cartilage to build a modern layered stack aesthetic.',
    price: 899,
    originalPrice: 1600,
    rating: 4.4,
    reviewsCount: 65,
    image: 'https://images.unsplash.com/photo-1629224316810-9d8805b95e76?w=600&auto=format&fit=crop&q=80',
    category: 'earrings',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold'],
    recipients: ['For Her', 'For Him'],
    occasions: ['Birthday']
  },
  {
    id: 'baroque-filigree-drops',
    name: 'Baroque Filigree Drop Earrings',
    description: 'Masterfully hand-etched Moroccan lace motifs. Solid silver drops of architectural elegance that capture and reflect candlelight beautifully.',
    price: 2150,
    originalPrice: 3900,
    rating: 4.7,
    reviewsCount: 140,
    image: 'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=600&auto=format&fit=crop&q=80',
    category: 'earrings',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Anniversary']
  },
  {
    id: 'aurora-hoop-medium',
    name: 'Aurora Borealis Twisted Hoops',
    description: 'Two interlocking twist strands: one high-shine silver, the other mirror-studded with premium zirconia. Designed for highly reflective dynamic shine.',
    price: 1650,
    originalPrice: 3000,
    rating: 4.9,
    reviewsCount: 257,
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80&sig=aurora-hoops',
    category: 'earrings',
    bestseller: true,
    isNew: true,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Birthday', 'Others']
  },
  {
    id: 'solitary-cz-studs',
    name: 'Solitary Brilliant CZ Studs',
    description: 'The absolute standard. Hypoallergenic 4-claw sterling setting hosting a certified brilliant cubic-zirconia gemstone for simple, pristine sparkle.',
    price: 1100,
    originalPrice: 2000,
    rating: 4.8,
    reviewsCount: 540,
    image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=600&auto=format&fit=crop&q=80&sig=solitary-cz-studs',
    category: 'earrings',
    bestseller: true,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her', 'For Him'],
    occasions: ['Birthday', 'Others']
  },
  {
    id: 'gothic-black-studs',
    name: 'Onyx Eclipse Studs',
    description: 'Bold contrast for him. Centering a flawless polished black onyx stone nested within deep channel-plated 925 sterling silver.',
    price: 1350,
    originalPrice: 2500,
    rating: 4.7,
    reviewsCount: 119,
    image: 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=600&auto=format&fit=crop&q=80&sig=gothic-black-studs',
    category: 'earrings',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver'],
    recipients: ['For Him'],
    occasions: ['Birthday']
  },
  {
    id: 'tassel-starburst-drops',
    name: 'Starburst Tassel Drop Earrings',
    description: 'Elegant linear drops consisting of micro-chains fluidly descending from a starry celestial starburst centerpiece. Pure sophistication.',
    price: 2750,
    originalPrice: 4900,
    rating: 5.0,
    reviewsCount: 94,
    image: 'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=600&auto=format&fit=crop&q=80&sig=tassel-drops',
    category: 'earrings',
    bestseller: true,
    isNew: true,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Anniversary']
  },
  {
    id: 'minimalist-threaders',
    name: 'Infinity Link Silver Threaders',
    description: 'A whisper-thin sterling chain designed to thread directly through the lobe, completed by comfortable high-shine infinity metal loops.',
    price: 1250,
    originalPrice: 2200,
    rating: 4.6,
    reviewsCount: 103,
    image: 'https://images.unsplash.com/photo-1588444839799-eb08ed7bc65b?w=600&auto=format&fit=crop&q=80&sig=minimalist-threaders',
    category: 'earrings',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold'],
    recipients: ['For Her'],
    occasions: ['Others']
  },
  {
    id: 'art-deco-emerald-drops',
    name: 'Art Deco Emerald Drops',
    description: 'Stately emerald-cut simulation gems crowned by classic geometric pave settings in heavy-plated sterling silver. Perfect statement wear.',
    price: 3100,
    originalPrice: 5500,
    rating: 4.9,
    reviewsCount: 164,
    image: 'https://images.unsplash.com/photo-1625796245224-fa304675bda3?w=600&auto=format&fit=crop&q=80',
    category: 'earrings',
    bestseller: true,
    isNew: false,
    polishColors: ['Silver', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Anniversary']
  },


  // --- ORIGINAL NECKLACES ---
  {
    id: 'solitaire-pendant',
    name: 'Solitaire Tear Pendant',
    description: 'A breathtaking teardrop pendant made of high-clarity simulated diamonds set in a bespoke 925 sterling silver cage. Includes a strong yet whisper-thin 18-inch adjustable silver chain.',
    price: 2700,
    originalPrice: 5400,
    rating: 4.9,
    reviewsCount: 312,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80',
    category: 'necklaces',
    bestseller: true,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Birthday', 'Anniversary']
  },
  {
    id: 'aura-collar',
    name: 'Imperial Silver Collar',
    description: 'The pinnacle of luxury necklace crafting. Interconnected solid 925 silver link meshes that rest flat gently on the collarbone. Imbued with anti-tarnish protective sealing.',
    price: 3900,
    originalPrice: 7999,
    rating: 5.0,
    reviewsCount: 48,
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&auto=format&fit=crop&q=80',
    category: 'necklaces',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver', 'Gold Plated'],
    recipients: ['For Her', 'For Him'],
    occasions: ['Anniversary', 'Others']
  },

  // --- ADDITIONAL NECKLACES ---
  {
    id: 'heart-locket-pendant',
    name: 'Secret Memoir Heart Locket',
    description: 'A beautifully secure sterling silver opening heart locket. Hand-engraved with fine foliage details and suspended from an anti-tarnish cable chain.',
    price: 1999,
    originalPrice: 3500,
    rating: 4.8,
    reviewsCount: 412,
    image: 'https://images.unsplash.com/photo-1590548784585-645d2b63587a?w=600&auto=format&fit=crop&q=80&sig=eternal-heart-locket',
    category: 'necklaces',
    bestseller: true,
    isNew: true,
    polishColors: ['Silver', 'Rose Gold'],
    recipients: ['For Her'],
    occasions: ['Birthday']
  },
  {
    id: 'interlocking-rings-necklace',
    name: 'Interlocking Russian Rings',
    description: 'Three interconnected, highly polished flat silver rings, representing Past, Present, and Future. Highly structural and deeply meaningful.',
    price: 2200,
    originalPrice: 3800,
    rating: 4.7,
    reviewsCount: 189,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80&sig=interlocking-rings',
    category: 'necklaces',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Anniversary']
  },
  {
    id: 'crescent-moon-necklace',
    name: 'Crescent Moonlit Pendant',
    description: 'A delicate horned crescent moon cast smoothly in sterling silver and dotted with beautiful star-scattered micro-zirconia studs.',
    price: 1450,
    originalPrice: 2600,
    rating: 4.9,
    reviewsCount: 320,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80&sig=crescent-moon',
    category: 'necklaces',
    bestseller: true,
    isNew: true,
    polishColors: ['Silver', 'Rose Gold'],
    recipients: ['For Her'],
    occasions: ['Birthday', 'Others']
  },
  {
    id: 'vintage-coin-medallion',
    name: 'Helios Vintage Coin Medallion',
    description: 'A heavy, detailed ancient Greek medallion replica minted in genuine raw-looking 925 pure silver. Extremely unique heirloom finish.',
    price: 2650,
    originalPrice: 4800,
    rating: 4.6,
    reviewsCount: 87,
    image: 'https://images.unsplash.com/photo-1611085583191-a3b1a30a5a2a?w=600&auto=format&fit=crop&q=80',
    category: 'necklaces',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver', 'Gold Plated'],
    recipients: ['For Her', 'For Him'],
    occasions: ['Others']
  },
  {
    id: 'minimalist-bar-pendant',
    name: 'Horizontal Sleek Bar Pendant',
    description: 'A simple geometric beam of mirrored silver hanging perfectly centered on a flat cable chain. Elegance understated.',
    price: 1150,
    originalPrice: 2000,
    rating: 4.7,
    reviewsCount: 243,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80&sig=sleek-bar',
    category: 'necklaces',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her', 'For Him'],
    occasions: ['Birthday']
  },
  {
    id: 'cuban-link-chain',
    name: 'Sterling Cuban Link Chain',
    description: 'Heavy architectural luxury for him. Highly reflectively diamond-cut solid flat curb links made of 100% thick premium sterling silver.',
    price: 3400,
    originalPrice: 5999,
    rating: 4.9,
    reviewsCount: 541,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80&sig=cuban-link',
    category: 'necklaces',
    bestseller: true,
    isNew: true,
    polishColors: ['Silver', 'Gold Plated'],
    recipients: ['For Him'],
    occasions: ['Anniversary', 'Others']
  },
  {
    id: 'mens-crucifix-cross',
    name: 'Imperial Cross Pendant',
    description: 'A stately, sleek, bevel-edged cross hand-forged in raw argent silver with secure loop bail. Includes heavy box chain.',
    price: 2100,
    originalPrice: 3800,
    rating: 4.8,
    reviewsCount: 167,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80&sig=mens-crucifix-cross',
    category: 'necklaces',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver'],
    recipients: ['For Him'],
    occasions: ['Birthday']
  },
  {
    id: 'royal-emerald-solitaire',
    name: 'Royal Emerald Cut Solitaire',
    description: 'A massive emerald-cut crystalline cubic-zirconia deep nested inside protective architectural bezel prongs. Demands absolute attention.',
    price: 3250,
    originalPrice: 5800,
    rating: 5.0,
    reviewsCount: 42,
    image: 'https://images.unsplash.com/photo-1625796245224-fa304675bda3?w=600&auto=format&fit=crop&q=80&sig=royal-emerald-solitaire',
    category: 'necklaces',
    bestseller: false,
    isNew: true,
    polishColors: ['Silver', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Anniversary']
  },
  {
    id: 'infinity-knot-necklace',
    name: 'Timeless Infinity Knot Necklace',
    description: 'A beautiful continuous silver loop, representing a secure and eternal bond. Handcrafted utilizing flexible pure silver thread.',
    price: 1750,
    originalPrice: 3000,
    rating: 4.8,
    reviewsCount: 204,
    image: 'https://images.unsplash.com/photo-1590548784585-645d2b63587a?w=600&auto=format&fit=crop&q=80&sig=infinity-knot-necklace',
    category: 'necklaces',
    bestseller: true,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold'],
    recipients: ['For Her'],
    occasions: ['Anniversary', 'Birthday']
  },
  {
    id: 'layered-satellite-choker',
    name: 'Layered Satellite Glimmer Choker',
    description: 'Two distinct nested lengths: one tight high-mirror snake chain, and a beautiful outer strand dotted with small reflective silver beads.',
    price: 1600,
    originalPrice: 2800,
    rating: 4.7,
    reviewsCount: 153,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80&sig=layered-satellite-choker',
    category: 'necklaces',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Others']
  },
  {
    id: 'geometric-cube-pendant',
    name: 'Geometric Origami Cube Lariat',
    description: 'An artistic 3D hollow origami-style cube sliding freely through a minimalist fine box chain. Fascinating modern design.',
    price: 1850,
    originalPrice: 3200,
    rating: 4.6,
    reviewsCount: 69,
    image: 'https://images.unsplash.com/photo-1590548784585-645d2b63587a?w=600&auto=format&fit=crop&q=80&sig=geometric-cube-pendant',
    category: 'necklaces',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold'],
    recipients: ['For Her', 'For Him'],
    occasions: ['Birthday']
  },


  // --- ORIGINAL BRACELETS ---
  {
    id: 'dainty-stack',
    name: 'Dainty Hearts Stack Bracelet',
    description: 'Elegant linked hearts bracelet crafted with 925 pure silver. Features a very secure lobster clasp and extension ring to perfectly fit wrist sizes from 6 to 8 inches in circumference.',
    price: 1350,
    originalPrice: 2700,
    rating: 4.5,
    reviewsCount: 167,
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&auto=format&fit=crop&q=80',
    category: 'bracelets',
    bestseller: true,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Birthday', 'Others']
  },
  {
    id: 'architectural-cuff',
    name: 'Aurelia Engraved Cuff',
    description: 'An open-front solid silver cuff with smooth modern organic borders. Adjustable shape to fit any wrist easily, detailed with a subtle 925 authenticity hallmark.',
    price: 1999,
    originalPrice: 3999,
    rating: 4.8,
    reviewsCount: 89,
    image: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&auto=format&fit=crop&q=80&sig=silver-weave-cuff',
    category: 'bracelets',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her', 'For Him'],
    occasions: ['Birthday', 'Others']
  },

  // --- ADDITIONAL BRACELETS ---
  {
    id: 'tennis-crystal-bracelet',
    name: 'Imperial Diamond Tennis Bracelet',
    description: 'A continuous, sparkling line of perfectly calibrated brilliant cubic zirconia diamonds individually set in double-hinged links of 925 silver. Absolute opulence.',
    price: 2990,
    originalPrice: 5200,
    rating: 4.9,
    reviewsCount: 512,
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&auto=format&fit=crop&q=80&sig=tennis-crystal-bracelet',
    category: 'bracelets',
    bestseller: true,
    isNew: true,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Anniversary']
  },
  {
    id: 'mens-leather-silver-weave',
    name: 'Gaelic Weave Leather Cuff',
    description: 'Combining rugged aesthetics. Intertwined, high-strength full grain leather completed with an ornate central Celtic plate handcrafted in hypoallergenic silver.',
    price: 2150,
    originalPrice: 3800,
    rating: 4.8,
    reviewsCount: 172,
    image: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&auto=format&fit=crop&q=80',
    category: 'bracelets',
    bestseller: true,
    isNew: false,
    polishColors: ['Silver'],
    recipients: ['For Him'],
    occasions: ['Birthday', 'Others']
  },
  {
    id: 'cable-twisted-cuff',
    name: 'Nautical Twisted Cable Cuff',
    description: 'An iconic marine cable twisted design finished with high-mirror, smooth solid silver spherical finials. Timeless wristwear.',
    price: 1800,
    originalPrice: 3100,
    rating: 4.7,
    reviewsCount: 98,
    image: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&auto=format&fit=crop&q=80&sig=cable-twisted-cuff',
    category: 'bracelets',
    bestseller: false,
    isNew: true,
    polishColors: ['Silver', 'Gold Plated'],
    recipients: ['For Her', 'For Him'],
    occasions: ['Others']
  },
  {
    id: 'celestial-charm-bracelet',
    name: 'Milkyway Celestial charm',
    description: 'A delightful fluid chain carrying five exquisite, dangling flat celestial charms: star, moon, comet, eclipse, and planet, detailed with crystal sparkles.',
    price: 2250,
    originalPrice: 4000,
    rating: 4.9,
    reviewsCount: 289,
    image: 'https://images.unsplash.com/photo-1611085797489-215579664281?w=600&auto=format&fit=crop&q=80&sig=celestial-charm',
    category: 'bracelets',
    bestseller: true,
    isNew: false,
    polishColors: ['Silver', 'Rose Gold'],
    recipients: ['For Her'],
    occasions: ['Birthday']
  },
  {
    id: 'figaro-chain-link',
    name: 'Classic Figaro Link Chain',
    description: 'Symmetric, flat diamond-cut repeating link pattern in genuine heavy solid silver. Closes with a sturdy high-tension lobster clasp.',
    price: 2400,
    originalPrice: 4200,
    rating: 4.7,
    reviewsCount: 145,
    image: 'https://images.unsplash.com/photo-1611085583191-a3b1a30a5a2a?w=600&auto=format&fit=crop&q=80&sig=figaro-chain-link',
    category: 'bracelets',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver', 'Gold Plated'],
    recipients: ['For Her', 'For Him'],
    occasions: ['Birthday']
  },
  {
    id: 'beaded-lava-stone',
    name: 'Onyx Beaded Balance Bracelet',
    description: 'Grounding aura wristwear. Alternating raw, porous vesicular lava rock beads and heavy, hand-polished sterling silver spherical spacer beads.',
    price: 1100,
    originalPrice: 1999,
    rating: 4.6,
    reviewsCount: 320,
    image: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&auto=format&fit=crop&q=80&sig=beaded-lava-stone',
    category: 'bracelets',
    bestseller: false,
    isNew: false,
    polishColors: ['Silver'],
    recipients: ['For Him'],
    occasions: ['Others']
  },
  {
    id: 'interlocking-bangle',
    name: 'Triple Interlocking Bangle Set',
    description: 'Three sleek, independent high-tensile silver round bangles that slip over the hand to roll fluidly together along the arm with delightful sound.',
    price: 3100,
    originalPrice: 5500,
    rating: 4.9,
    reviewsCount: 74,
    image: 'https://images.unsplash.com/photo-1618403088890-3d9ff6f4c8be?w=600&auto=format&fit=crop&q=80',
    category: 'bracelets',
    bestseller: false,
    isNew: true,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Anniversary']
  },
  {
    id: 'personalized-nameplate-bar',
    name: 'Signature Nameplate Bar Chain',
    description: 'A classic smooth-polished flat ID tag bar integrated into an adjustable double-rope cable chain. Perfect for custom engravings.',
    price: 1700,
    originalPrice: 3000,
    rating: 4.8,
    reviewsCount: 199,
    image: 'https://images.unsplash.com/photo-1611085797489-215579664281?w=600&auto=format&fit=crop&q=80',
    category: 'bracelets',
    bestseller: true,
    isNew: true,
    polishColors: ['Silver', 'Rose Gold', 'Gold Plated'],
    recipients: ['For Her'],
    occasions: ['Birthday', 'Others']
  },
  {
    id: 'royal-silver-anklet',
    name: 'Royal Filigree Anklet',
    description: 'An intricately crafted 925 sterling silver anklet embellished with tiny, melodic silver beads designed to rest delicately along the ankle.',
    price: 2999,
    originalPrice: 4500,
    rating: 4.9,
    reviewsCount: 38,
    image: 'https://images.unsplash.com/photo-1543294001-f7cbfe92237e?w=600&auto=format&fit=crop&q=80',
    category: 'anklets',
    bestseller: true,
    isNew: true,
    polishColors: ['Silver', 'Rose Gold'],
    recipients: ['For Her'],
    occasions: ['Birthday', 'Others']
  }
];

export const PROMOTIONS: Promotion[] = [
  {
    code: 'SILVER25',
    discountPercent: 25,
    description: 'Get Flat 25% OFF on our elegant Silver Affair collection!'
  },
  {
    code: 'GOLDY10',
    discountPercent: 10,
    description: 'Get 10% off items for special festive polishes.'
  }
];

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    userName: 'Kavya S.',
    rating: 5,
    comment: 'Absolutely stunning! The silver has this mirror-like finish and feels solid. I wear the studs every day and they do not irritate my sensitive ears.',
    date: '2026-05-20'
  },
  {
    id: 'r2',
    userName: 'Priya M.',
    rating: 5,
    comment: 'Very high quality. Hallmarked 925 so I feel safe about the authenticity. Got so many compliments already.',
    date: '2026-06-02'
  },
  {
    id: 'r3',
    userName: 'Rohan J.',
    rating: 4,
    comment: 'Gifted the solitaire ring to my fiancée and she loved it. The sizing guide was accurate. Fast shipping too.',
    date: '2026-06-10'
  }
];
